# Generated by Django 5.2.4 on 2025-07-14 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comprador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprador",
                "verbose_name_plural": "Compradores",
                "ordering": ["-data_cadastro"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "produto",
                    models.CharField(
                        choices=[
                            ("camiseta-marrom", "Camiseta One Way Marrom"),
                            ("camiseta-jesus", "Camiseta Jesus"),
                            ("camiseta-oneway-branca", "Camiseta ONE WAY Off White"),
                            ("camiseta-the-way", "Camiseta The Way"),
                        ],
                        max_length=100,
                        verbose_name="Produto",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        choices=[("P", "P"), ("M", "M"), ("G", "G"), ("GG", "GG")],
                        max_length=5,
                        verbose_name="Tamanho",
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("pix", "PIX (5% desconto)"),
                            ("2x", "Cartão 2x sem juros"),
                            ("4x", "Cartão até 4x"),
                            ("credit_card", "Cartão de Crédito"),
                            ("debit_card", "Cartão de Débito"),
                            ("ticket", "Boleto"),
                            ("bank_transfer", "Transferência"),
                            ("account_money", "Dinheiro em Conta"),
                        ],
                        max_length=20,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Referência Externa"
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID Pagamento MP",
                    ),
                ),
                (
                    "preference_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID Preferência MP",
                    ),
                ),
                (
                    "merchant_order_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID Ordem Comerciante",
                    ),
                ),
                (
                    "status_pagamento",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("in_process", "Processando"),
                            ("rejected", "Rejeitado"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status do Pagamento",
                    ),
                ),
                (
                    "data_pedido",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Pedido"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "comprador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.comprador",
                        verbose_name="Comprador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-data_pedido"],
            },
        ),
    ]
