# Generated by Django 4.2.16 on 2025-07-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("pix", "PIX (5% desconto)"),
                    ("2x", "Cartão 2x sem juros"),
                    ("4x", "Cartão até 4x"),
                    ("paypal", "PayPal"),
                    ("credit_card", "Cartão de Crédito"),
                    ("debit_card", "Cartão de Débito"),
                    ("ticket", "Boleto"),
                    ("bank_transfer", "Transferência"),
                    ("account_money", "Dinheiro em Conta"),
                ],
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="payment_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="ID Pagamento MP/PayPal",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="preference_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ID Preferência MP/Ordem PayPal",
            ),
        ),
    ]
