# Generated by Django 4.2.16 on 2025-07-19 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "pedidos",
            "0002_alter_pedido_forma_pagamento_alter_pedido_payment_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "produto",
                    models.CharField(
                        choices=[
                            ("camiseta-marrom", "Camiseta One Way Marrom"),
                            ("camiseta-jesus", "Camiseta Jesus"),
                            ("camiseta-oneway-branca", "Camiseta ONE WAY Off White"),
                            ("camiseta-the-way", "Camiseta The Way"),
                        ],
                        max_length=100,
                        verbose_name="Produto",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        choices=[("P", "P"), ("M", "M"), ("G", "G"), ("GG", "GG")],
                        max_length=5,
                        verbose_name="Tamanho",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Unitário"
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="pedidos.pedido",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido",
                "verbose_name_plural": "Itens do Pedido",
                "unique_together": {("pedido", "produto", "tamanho")},
            },
        ),
    ]
