# Generated by Django 4.2.16 on 2025-07-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_migrate_pedidos_to_itempedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Produto"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug (para URL)")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                (
                    "preco_custo",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço de Custo"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.IntegerField(default=0, verbose_name="Ordem de Exibição"),
                ),
                (
                    "json_key",
                    models.CharField(
                        help_text="Chave no products.json para compatibilidade",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.AddField(
            model_name="pedido",
            name="estoque_decrementado",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o estoque já foi decrementado para este pedido",
                verbose_name="Estoque Decrementado",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("pix", "PIX (5% desconto)"),
                    ("2x", "Cartão 2x sem juros"),
                    ("4x", "Cartão até 4x"),
                    ("paypal", "PayPal"),
                    ("credit_card", "Cartão de Crédito"),
                    ("debit_card", "Cartão de Débito"),
                    ("ticket", "Boleto"),
                    ("bank_transfer", "Transferência"),
                    ("account_money", "Dinheiro em Conta"),
                    ("presencial", "Pagamento Presencial"),
                ],
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.CreateModel(
            name="ProdutoTamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        choices=[("P", "P"), ("M", "M"), ("G", "G"), ("GG", "GG")],
                        max_length=5,
                        verbose_name="Tamanho",
                    ),
                ),
                ("estoque", models.IntegerField(default=0, verbose_name="Estoque")),
                (
                    "disponivel",
                    models.BooleanField(default=True, verbose_name="Disponível"),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tamanhos",
                        to="pedidos.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tamanho do Produto",
                "verbose_name_plural": "Tamanhos dos Produtos",
                "ordering": ["produto", "tamanho"],
                "unique_together": {("produto", "tamanho")},
            },
        ),
        migrations.AddField(
            model_name="itempedido",
            name="produto_tamanho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pedidos.produtotamanho",
                verbose_name="Produto/Tamanho (Novo Sistema)",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="produto_tamanho",
            field=models.ForeignKey(
                blank=True,
                help_text="Referência ao novo sistema de controle de estoque",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pedidos.produtotamanho",
                verbose_name="Produto/Tamanho (Novo Sistema)",
            ),
        ),
    ]
