# Generated by Django 4.2.16 on 2025-07-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0006_adicionar_movimentacao_estoque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempedido",
            name="produto",
            field=models.CharField(
                choices=[
                    ("camiseta-marrom", "Camiseta One Way Marrom"),
                    ("camiseta-jesus", "Camiseta Jesus"),
                    ("camiseta-oneway-branca", "Camiseta ONE WAY Off White"),
                    ("camiseta-the-way", "Camiseta The Way"),
                    ("almoco-sabado", "Almoço - Sábado"),
                    ("jantar-sabado", "Jantar - Sábado"),
                ],
                max_length=100,
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="tamanho",
            field=models.CharField(
                choices=[
                    ("P", "P"),
                    ("M", "M"),
                    ("G", "G"),
                    ("GG", "GG"),
                    ("UNICO", "Único"),
                ],
                max_length=5,
                verbose_name="Tamanho",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="produto",
            field=models.CharField(
                choices=[
                    ("camiseta-marrom", "Camiseta One Way Marrom"),
                    ("camiseta-jesus", "Camiseta Jesus"),
                    ("camiseta-oneway-branca", "Camiseta ONE WAY Off White"),
                    ("camiseta-the-way", "Camiseta The Way"),
                    ("almoco-sabado", "Almoço - Sábado"),
                    ("jantar-sabado", "Jantar - Sábado"),
                ],
                max_length=100,
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="tamanho",
            field=models.CharField(
                choices=[
                    ("P", "P"),
                    ("M", "M"),
                    ("G", "G"),
                    ("GG", "GG"),
                    ("UNICO", "Único"),
                ],
                max_length=5,
                verbose_name="Tamanho",
            ),
        ),
        migrations.AlterField(
            model_name="produtotamanho",
            name="tamanho",
            field=models.CharField(
                choices=[
                    ("P", "P"),
                    ("M", "M"),
                    ("G", "G"),
                    ("GG", "GG"),
                    ("UNICO", "Único"),
                ],
                max_length=5,
                verbose_name="Tamanho",
            ),
        ),
    ]
