# Generated by Django 4.2.16 on 2025-07-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0007_adicionar_produtos_alimentacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempedido",
            name="produto",
            field=models.CharField(
                choices=[
                    ("camiseta-marrom", "Camiseta One Way Marrom"),
                    ("camiseta-jesus", "Camiseta Jesus"),
                    ("camiseta-oneway-branca", "Camiseta ONE WAY Off White"),
                    ("camiseta-the-way", "Camiseta The Way"),
                    ("almoco-sabado", "Almoço - Sábado"),
                    ("jantar-sabado", "Jantar - Sábado"),
                    ("espetinho-carne", "Espetinho de Carne Bovina"),
                    ("espetinho-frango", "Espetinho Medalhão de Frango"),
                    ("espetinho-linguica", "Espetinho de Linguiça"),
                    ("adicional-mandioca", "Adicional: Mandioca + Vinagrete"),
                ],
                max_length=100,
                verbose_name="Produto",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="produto",
            field=models.CharField(
                choices=[
                    ("camiseta-marrom", "Camiseta One Way Marrom"),
                    ("camiseta-jesus", "Camiseta Jesus"),
                    ("camiseta-oneway-branca", "Camiseta ONE WAY Off White"),
                    ("camiseta-the-way", "Camiseta The Way"),
                    ("almoco-sabado", "Almoço - Sábado"),
                    ("jantar-sabado", "Jantar - Sábado"),
                    ("espetinho-carne", "Espetinho de Carne Bovina"),
                    ("espetinho-frango", "Espetinho Medalhão de Frango"),
                    ("espetinho-linguica", "Espetinho de Linguiça"),
                    ("adicional-mandioca", "Adicional: Mandioca + Vinagrete"),
                ],
                max_length=100,
                verbose_name="Produto",
            ),
        ),
    ]
