# Generated by Django 4.2.16 on 2025-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0008_adicionar_produtos_espetinhos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempedido",
            name="preco_unitario",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Preço Unitário"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Preço"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Preço"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_custo",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Preço de Custo"
            ),
        ),
    ]
