# Generated by Django 5.2.4 on 2025-07-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0009_aumentar_max_digits_preco"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="data_email_enviado",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora em que o email de confirmação foi enviado",
                null=True,
                verbose_name="Data do envio do email",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="email_confirmacao_enviado",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o email de confirmação já foi enviado para este pedido",
                verbose_name="Email de confirmação enviado",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="usuario_email_enviado",
            field=models.CharField(
                blank=True,
                help_text="Nome do usuário admin que enviou o email de confirmação",
                max_length=100,
                verbose_name="Usuário que enviou o email",
            ),
        ),
    ]
