# Generated by Django 5.2.4 on 2025-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0010_pedido_data_email_enviado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedido",
            name="data_entrega",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora em que o item foi entregue",
                null=True,
                verbose_name="Data da Entrega",
            ),
        ),
        migrations.AddField(
            model_name="itempedido",
            name="entregue",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o item já foi entregue ao comprador",
                verbose_name="Entregue",
            ),
        ),
        migrations.AddField(
            model_name="itempedido",
            name="usuario_entrega",
            field=models.CharField(
                blank=True,
                help_text="Nome do usuário que registrou a entrega",
                max_length=100,
                verbose_name="Entregue por",
            ),
        ),
    ]
