# Generated by Django 5.2.4 on 2025-07-31 15:44

from django.db import migrations


def popular_quantidade_entregue(apps, schema_editor):
    """
    Popular campo quantidade_entregue baseado no campo entregue existente
    Se entregue=True, então quantidade_entregue = quantidade
    Se entregue=False, então quantidade_entregue = 0
    """
    ItemPedido = apps.get_model('pedidos', 'ItemPedido')
    
    # Atualizar todos os itens entregues
    itens_entregues = ItemPedido.objects.filter(entregue=True)
    for item in itens_entregues:
        item.quantidade_entregue = item.quantidade
        item.save()
    
    print(f"✅ Populados {itens_entregues.count()} itens como totalmente entregues")
    
    # Itens não entregues já têm quantidade_entregue=0 por padrão
    itens_pendentes = ItemPedido.objects.filter(entregue=False).count()
    print(f"ℹ️  {itens_pendentes} itens permanecem como pendentes (quantidade_entregue=0)")


def reverter_quantidade_entregue(apps, schema_editor):
    """
    Reverter a migração - resetar quantidade_entregue para 0
    """
    ItemPedido = apps.get_model('pedidos', 'ItemPedido')
    ItemPedido.objects.all().update(quantidade_entregue=0)
    print("🔄 Quantidade entregue resetada para todos os itens")


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0012_adicionar_quantidade_entregue"),
    ]

    operations = [
        migrations.RunPython(
            popular_quantidade_entregue,
            reverse_code=reverter_quantidade_entregue,
        ),
    ]
